### ISSUE TITLE
xfce panel looks ugly

### ISSUE THREAD

**Issue by brudolp** [paullinuxthemer/McOS-XFCE-Edition#1]
love your theme and really would like to use it, however anything else than a dark panel looks not that nice:
https://i.imgur.com/WZZbvc1.png
plugins: xfce4-pulseaudio-plugin(0.4.1), clipman, clock, vala-appmenu and xfce4-notifyd
using arch(antergos) btw.

**Comment by erayerdin** [comment]
The only quirk is the panel being dark.

**Comment by s1-ranjan** [comment]
> love your theme and really would like to use it, however anything else than a dark panel looks not that nice:
> https://i.imgur.com/WZZbvc1.png
> plugins: xfce4-pulseaudio-plugin(0.4.1), clipman, clock, vala-appmenu and xfce4-notifyd
> using arch(antergos) btw.

I think this can be fixed by making some edit in gtk3 file in the theam, I tried with following modification and I hope this can fix this problem:

.xfce4-panel.panel {
  background-color: #393939;
  color: #DADADA; }
  .xfce4-panel.panel button.flat, .xfce4-panel.panel button.sidebar-button {
    color: #DADADA;
    background-color: rgba(52, 52, 52, 0);
    border-radius: 0;
    border: none; }
    .xfce4-panel.panel button.flat:hover, .xfce4-panel.panel button.sidebar-button:hover {
      border: none;
      background-color: #4e4e4e; }
    .xfce4-panel.panel button.flat:active, .xfce4-panel.panel button.sidebar-button:active, .xfce4-panel.panel button.flat:checked, .xfce4-panel.panel button.sidebar-button:checked {
      color: #ffffff;
      border: none;
      background-color: #92b372; }

**Comment by brudolp** [comment]
thx, not using xfce anymore though :P
